<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>DNSChanger</AssemblyName>
    <RootNamespace>DNSChangerApp</RootNamespace>
    <Version>2.2.0</Version>
    <AssemblyVersion>2.2.0.0</AssemblyVersion>
    <FileVersion>2.2.0.0</FileVersion>
    <Authors>Hadooshi</Authors>
    <Company>Hadooshi</Company>
    <Product>Iran DNS Toolbox</Product>
    <Description>Windows 10/11 DNS Changer &amp; Anti-Sanction Toolbox by Hadooshi</Description>
    <Copyright>Copyright © 2026 Hadooshi</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

</Project>
